# for dev/master branch
-
  version: 1.0.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  environment:
    target_version: net46
  build_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.6;DefineConstants="DEBUG;TRACE";OutPutPath=bin\$(configuration)\$(target_version)
  test_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.6;DefineConstants="DEBUG;TRACE";OutPutPath=bin\$(configuration)\$(target_version)
  - ps: .\run-tests.ps1 -Configuration $(env:configuration) -TargetVersion $(env:target_version)

# for release/all branch
-
  version: 1.0.0.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    target_version: net46
    github_auth_token:
      secure: 3tp7rCl4cvk/WDYBaeodIlmalNiYVWQYxE1wmVU7aMbkMKP0WtlMjjOU2yhX0D4n
  build_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE";OutPutPath=bin\$(configuration)\$(target_version)
  test_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE";OutPutPath=bin\$(configuration)\$(target_version)
  - ps: .\run-tests.ps1 -Configuration $(env:configuration) -TargetVersion $(env:target_version)
  after_test:
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE";OutPutPath=bin\$(configuration)\$(target_version)
  - ps: .\run-tests.ps1 -Configuration $(env:configuration) -TargetVersion $(env:target_version)
  artifacts:
  - path: '**\Aliencube.ScriptCs.AzureFunctions.*.nupkg'
    name: Aliencube.ScriptCs.AzureFunctions
  deploy:
  - provider: NuGet
    api_key:
      secure: ZdI7BA2YRQg/yRMPbRGTTJeGWj3X3o8kNhf4LeA5YkV072GpmKwQ3aW+KVgMbkZX
    artifact: Aliencube.ScriptCs.AzureFunctions
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release/all
