# for dev/master branch
-
  version: 0.16.1.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - dev
    - master
  skip_tags: true
  image: Visual Studio 2015
  configuration: Debug
  platform: Any CPU
  build_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.6;DefineConstants="DEBUG;TRACE";OutPutPath=bin\Debug\net46
  test_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Debug;TargetFrameworkVersion=v4.6;DefineConstants="DEBUG;TRACE";OutPutPath=bin\Debug\net46
  - ps: .\run-tests.ps1 -Configuration Debug -TargetVersion net46

# for release/all branch
-
  version: 0.16.1.{build}
  pull_requests:
    do_not_increment_build_number: true
  branches:
    only:
    - release/all
  skip_tags: true
  image: Visual Studio 2015
  configuration: Release
  platform: Any CPU
  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'
  environment:
    project_name: ScriptCs.AzureFunctions
  build_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE;TEST";OutPutPath=bin\Release\net46
  test_script:
  - cmd: tools\nuget restore ScriptCs.AzureFunctions.sln
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE;TEST";OutPutPath=bin\Release\net46
  - ps: .\run-tests.ps1 -Configuration Release -TargetVersion net46
  after_test:
  - cmd: msbuild ScriptCs.AzureFunctions.sln /t:ReBuild /v:minimal /p:Configuration=Release;TargetFrameworkVersion=v4.6;DefineConstants="TRACE;TEST";OutPutPath=bin\Release\net46
  - ps: .\build-package.ps1 -Version "$env:APPVEYOR_BUILD_VERSION"
  artifacts:
  - path: '**\ScriptCs.AzureFunctions.*.nupkg'
    name: ScriptCs.AzureFunctions
  deploy:
  - provider: NuGet
    api_key: $(nuget_api_key)
    artifact: ScriptCs.AzureFunctions
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  - provider: GitHub
    tag: v$(appveyor_build_version)
    description: $(project_name)-v$(appveyor_build_version) has been released
    auth_token: $(github_auth_token)
    artifact: ScriptCs.AzureFunctions
    on:
      branch: release/all
      platform: Any CPU
      configuration: Release
  after_deploy:
  - cmd: git config --global credential.helper store
  - ps: Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:github_auth_token):x-oauth-basic@github.com`n"
  - cmd: git push origin --delete release/all
